FROM inetsoftware/windows-dotnet
MAINTAINER contact@inetsoftware.de

# install wixtoolset
RUN choco install -y wixtoolset --version 3.10.2.2516

# install msbuild
RUN choco install -y microsoft-build-tools --version 14.0.25420.1
