# version: '2.1'
services:
    base:
        build: ./alpine-java-base
        image: 'inetsoftware/alpine-java-base'
        networks:
            - default

    ssh:
        build: ./alpine-jenkins-base
        image: 'inetsoftware/alpine-jenkins-base'
        networks:
            - default

    ssh-docker:
        build:
            context: ./alpine-jenkins-base
            args:
                - BASE=eclipse-temurin:17-jdk-alpine
        image: 'inetsoftware/alpine-jenkins-base:ssh-docker'
        networks:
            - default

    docker:
        build:
            context: ./alpine-docker-compose
            extra_hosts:
                - "registry.npmjs.org:104.16.26.34"
        image: 'inetsoftware/alpine-docker-compose'
        networks:
            - default

    gradle:
        build:
            context: ./alpine-java-gradle
            extra_hosts:
                - "downloads.sourceforge.net:204.68.111.105"
                - "vorboss.dl.sourceforge.net:5.10.152.194"
                - "ufpr.dl.sourceforge.net:200.17.212.49"
                - "netcologne.dl.sourceforge.net:78.35.24.122"
                - "deac-riga.dl.sourceforge.net:89.111.52.100"
                - "deac-ams.dl.sourceforge.net:185.34.27.55"
                - "altushost-swe.dl.sourceforge.net:79.142.76.130"
                - "jaist.dl.sourceforge.net:150.65.7.130"
                - "dl-cdn.alpinelinux.org:146.75.122.132"

        image: 'inetsoftware/alpine-java-gradle'
        networks:
            - default

    tesseract:
        build: ./alpine-gradle-tesseract
        image: 'inetsoftware/alpine-gradle-tesseract'
        networks:
            - default

networks:
    default:
        driver:  bridge
        enable_ipv6: false
