# version: '2.1'
services:
    base:
        build: ./alpine-java-base
        image: 'inetsoftware/alpine-java-base'
        networks:
            - default

    ssh:
        build: ./alpine-jenkins-base
        image: 'inetsoftware/alpine-jenkins-base'
        networks:
            - default

    ssh-docker:
        build:
            context: ./alpine-jenkins-base
            args:
                - BASE=eclipse-temurin:17-jdk-alpine
        image: 'inetsoftware/alpine-jenkins-base:ssh-docker'
        networks:
            - default

    docker:
        build:
            context: ./alpine-docker-compose
            extra_hosts:
                - "registry.npmjs.org:104.16.26.34"
        image: 'inetsoftware/alpine-docker-compose'
        networks:
            - default

    gradle:
        build:
            context: ./alpine-java-gradle
            extra_hosts:
                - "downloads.sourceforge.net:204.68.111.105"

        image: 'inetsoftware/alpine-java-gradle'
        networks:
            - default

    tesseract:
        build: ./alpine-gradle-tesseract
        image: 'inetsoftware/alpine-gradle-tesseract'
        networks:
            - default

networks:
    default:
        driver:  bridge
        enable_ipv6: false
