version: '2'
services:
    base:
        build: ./alpine-jenkins-base
        image: 'inetsoftware/alpine-jenkins-base'

    docker:
        build:
            context: ./alpine-docker-compose
            extra_hosts:
                - "registry.npmjs.org:104.16.26.34"
        image: 'inetsoftware/alpine-docker-compose'

    gradle:
        build: ./alpine-java-gradle
        image: 'inetsoftware/alpine-java-gradle'

    tesseract:
        build: ./alpine-gradle-tesseract
        image: 'inetsoftware/alpine-gradle-tesseract'
