version: '2.1'
services:
    base:
        build: ./alpine-jenkins-base
        image: 'inetsoftware/alpine-jenkins-base'

    docker:
        build: ./alpine-docker-compose
        image: 'inetsoftware/alpine-docker-compose'

    gradle:
        build: ./alpine-java-gradle
        image: 'inetsoftware/alpine-java-gradle'

    tesseract:
        build: ./alpine-gradle-tesseract
        image: 'inetsoftware/alpine-gradle-tesseract'
