# version: '2.1'
services:
    base:
        build: ./alpine-java-base
        image: 'inetsoftware/alpine-java-base'

    ssh:
        build: ./alpine-jenkins-base
        image: 'inetsoftware/alpine-jenkins-base'

    ssh-docker:
        build:
            context: ./alpine-jenkins-base
            extra_hosts:
                - "github.com:140.82.121.3"
                - "objects.githubusercontent.com:185.199.111.133"
            args:
                - BASE=eclipse-temurin:11-jdk-alpine
        image: 'inetsoftware/alpine-jenkins-ssh-docker'

    docker:
        build:
            context: ./alpine-docker-compose
            extra_hosts:
                - "github.com:140.82.121.3"
                - "objects.githubusercontent.com:185.199.111.133"
        image: 'inetsoftware/alpine-docker-compose'

    gradle:
        build:
            context: ./alpine-java-gradle
            extra_hosts:
                - "downloads.sourceforge.net:204.68.111.105"

        image: 'inetsoftware/alpine-java-gradle'

    tesseract:
        build: ./alpine-gradle-tesseract
        image: 'inetsoftware/alpine-gradle-tesseract'
