FROM inetsoftware/windows-java-gradle
MAINTAINER contact@inetsoftware.de

# install .NET4.5
RUN choco install -y dotnet4.5.1

# .NET 3.5 assemblies
# RUN choco install windows-sdk-7.0

# .NET 4.0 assemblies
# RUN choco install windows-sdk-7.1

# .NET 4.5 assemblies
# RUN choco install windows-sdk-8.0

# .NET 4.5.1 assemblies
RUN choco install windows-sdk-8.1

# .NET 4.6 assemblies
# RUN choco install windows-sdk-10
