services:
    squash:
        build:
            context: .
            extra_hosts:
                - "github.com:140.82.121.3"
                - "objects.githubusercontent.com:185.199.111.133"
        image: inetsoftware/docker-squash
