version: '2.1'
services:
    choco:
        build: ./windows-chocolatey
        image: 'inetsoftware/windows-chocolatey'

    base:
#        build: ./windows-openssh
        build: ./windows-jenkins-base
        image: 'inetsoftware/windows-jenkins-base'

    java:
        build: ./windows-java-gradle
        image: 'inetsoftware/windows-java-gradle'

    tools:
        build: ./windows-tools
        image: 'inetsoftware/windows-tools'

    sdk:
        build: ./windows-sdk
        image: 'inetsoftware/windows-sdk'

    reportreader:
        build: ./windows-reportreader
        image: 'inetsoftware/windows-reportreader'

    wixtoolset:
        build: ./windows-wixtoolset
        image: 'inetsoftware/windows-wixtoolset'

    crystalreports:
        build: ./windows-crystalreports
        image: 'inetsoftware/windows-crystalreports'

    uwp:
        build: ./windows-uwp
        image: 'inetsoftware/windows-uwp'
