version: '2'
services:
    choco:
        build: ./windows-chocolatey
        image: 'inetsoftware/windows-chocolatey'

    base:
        build: ./windows-jenkins-base
        image: 'inetsoftware/windows-jenkins-base'

    java:
        build: ./windows-java-gradle
        image: 'inetsoftware/windows-java-gradle'

    dotnet:
        build: ./windows-dotnet
        image: 'inetsoftware/windows-dotnet'

    wixtoolset:
        build: ./windows-wixtoolset
        image: 'inetsoftware/windows-wixtoolset'

    visualstudio:
        build: ./windows-visualstudio
        image: 'inetsoftware/windows-visualstudio'

    setupbuilder:
        build: ./windows-visualstudio
        image: 'inetsoftware/windows-setupbuilder'
