consul-server:
    image: "voxxit/consul:latest"
    container_name: "consul-server"
    hostname: "consul-server"
    ports:
        - "8400:8400"
        - "8500:8500"
        - "53:53"
    command: "agent -data-dir /data -server -bootstrap -ui-dir /ui -client=0.0.0.0"

registrator:
    command: "consul://consul-server:8500"
    image: "gliderlabs/registrator:latest"
    links:
        - "consul-server"
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"

jenkins-discovery-data:
    image: "inetsoftware/jenkins-discovery"

router:
    image: "seges/nginx-consul:1.9.0"
    volumes_from:
        - "jenkins-discovery-data"
    ports:
        - "80:80"
        - "443:443"