version: '2'

services:
    # Build the Data Image from the current folder
    # It contains
    jenkins-discovery-data:
        build: "."
        container_name: "discovery-data"
        image: "inetsoftware/jenkins-discovery-data"
        restart: "always"
        volumes:
            - "/tmp/consul-output:/etc/consul-template/output"

    consul-server:
        container_name: "consul-server"
        image: "voxxit/consul:latest"
        restart: "always"
        hostname: "consul-server"
        ports:
            # - "53:53"
            - "8400:8400"
            - "8500:8500"
        command: "agent -bootstrap-expect=1 -data-dir /data -server -ui-dir /ui -client=0.0.0.0 -advertise=$HOST_ADDRESS"
    
    registrator:
        image: "gliderlabs/registrator:latest"
        command: "consul://consul-server:8500"
        container_name: "registrator"
        restart: "always"
        links:
            - "consul-server"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
    
    router:
        image: "seges/nginx-consul:1.9.9"
        container_name: "router"
        restart: "always"
        volumes_from:
            - "jenkins-discovery-data"
        ports:
            - "80:80"
            - "443:443"
