# version: '2.1'
services:
    choco:
        build:
            context: ../windows/windows-chocolatey
            args:
                SDK_TAG: ${SDK_TAG}
        image: 'inetsoftware/windows-chocolatey:${SDK_TAG}'

    base:
        build:
            context: ../windows/windows-jenkins-base
            args:
                SDK_TAG: ${SDK_TAG}

        image: 'inetsoftware/windows-jenkins-base:${SDK_TAG}'

    java:
        build:
            context: ../windows/windows-java-gradle
            args:
                SDK_TAG: ${SDK_TAG}
        image: 'inetsoftware/windows-java-gradle:${SDK_TAG}'

    vs2019:
        build:
            context: ../windows/windows-vs-2019
            args:
                SDK_TAG: ${SDK_TAG}
        image: 'inetsoftware/windows-vs-2019'
        