version: '2.1'
services:
    tesseract:
        image: 'inetsoftware/alpine-tesseract'
        build:
            context: '.'
            args:
                SHA: master
                PKGVER: 4.1.1
                PKGREL: 2
    tesseract513:
        image: 'inetsoftware/alpine-tesseract'
        tty: true
        build:
            context: '.'
            args:
                SHA: 71af4542990adae6d9f31d6657068bc0139c6ec4
                PKGVER: 5.3.1
                PKGREL: 1
    tesseract412:
        image: 'inetsoftware/alpine-tesseract:4.1.2'
        build:
            context: '.'
            args:
                SHA: d358270dd4d77da4aaa3e8372010b1972472c166
                PKGVER: 4.1.2
                PKGREL: 1
    tesseract411:
        image: 'inetsoftware/alpine-tesseract:4.1.1'
        build:
            context: '.'
            args:
                SHA: 75103040c94ffd7fe5e4e3dfce0a7e67a8420849
                PKGVER: 4.1.1
                PKGREL: 1
    tesseract410:
        image: 'inetsoftware/alpine-tesseract:4.1.0'
        build:
            context: '.'
            args:
                SHA: 5280bbcade4e2dec5eef439a6e189504c2eadcd9
                PKGVER: 4.1.0
                PKGREL: 1
